# Generated by Django 4.1.7 on 2023-03-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_counterparty', models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], default=1, verbose_name='Роль')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('debt', models.FloatField(max_length=255, verbose_name='Задолженность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('provider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier_network.counterparty', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагент',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода продукта на рынок')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier_network.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contacts', models.PositiveSmallIntegerField(choices=[(1, 'Email'), (2, 'Страна'), (3, 'Город'), (4, 'Улица'), (5, 'Номер дома')], default=5, verbose_name='Тип контакта')),
                ('contact', models.CharField(max_length=255, verbose_name='Контакт')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier_network.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакт',
            },
        ),
    ]
