# Generated by Django 4.1.7 on 2023-03-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_network', '0003_alter_counterparty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='city',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='country',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='street',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='supplier_network.counterparty', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='type_counterparty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], default=0, verbose_name='Роль'),
        ),
    ]
